// categories for sales-1
export const categories = [
  {
    id: "ecc42ce0-f941-4702-8c53-c822e4b8178c",
    name: "Furniture",
    icon: "Sofa",
    image: null,
    slug: "furniture",
    parent: [],
    description: null,
    for: { demo: "sales-1", type: "categories" },
  },
  {
    id: "d0f90d4f-46a5-495a-a24f-ee82734eb703",
    name: "Women",
    icon: "WomenDress",
    image: null,
    slug: "women",
    parent: [],
    description: null,
    for: { demo: "sales-1", type: "categories" },
  },
  {
    id: "96a7bd22-c97e-4c07-aa70-56fe7dbdc3ec",
    name: "Electronics",
    icon: "Camera",
    image: null,
    slug: "electronics",
    parent: [],
    description: null,
    for: { demo: "sales-1", type: "categories" },
  },
  {
    id: "431009f1-1e32-4038-8b8e-be3cc9dc1c86",
    name: "Cosmetics",
    icon: "BeautyProducts",
    image: null,
    slug: "cosmetics",
    parent: [],
    description: null,
    for: { demo: "sales-1", type: "categories" },
  },
];


// categories for sales-2
export const categoriesTwo = [
  {
    id: "3a35ea11-4791-4477-8ced-18437d421ee2",
    name: "Računari",
    icon: "Computer",
    image: null,
    slug: "racunari",
    parent: [],
    description: null,
    for: { demo: "sales-1", type: "categories" },
  },
  {
    id: "5cff024a-d7fd-4b58-a8ab-ecb6638be74b",
    name: "Laptopi",
    icon: "Laptop",
    image: null,
    slug: "laptopi",
    parent: [],
    description: null,
    for: { demo: "sales-1", type: "categories" },
  },
  {
    id: "740e1b21-8540-4180-b425-71146ea28d59",
    name: "Apple",
    icon: "Console",
    image: null,
    slug: "konzole",
    parent: [],
    description: null,
    for: { demo: "sales-1", type: "categories" },
  },
  {
    id: "efbff951-9b59-436a-90e0-b92c37bf464f",
    name: "Mobiteli",
    icon: "Phone",
    image: null,
    slug: "mobiteli",
    parent: [],
    description: null,
    for: { demo: "sales-1", type: "categories" },
  },
  {
    id: "740e1b21-8540-4180-b425-71146ea28d60",
    name: "Monitori",
    icon: "Monitor",
    image: null,
    slug: "monitori",
    parent: [],
    description: null,
    for: { demo: "sales-1", type: "categories" },
  },
  {
    id: "d3415086-c10f-4490-aec0-90cf72a4e69d",
    name: "Računarska oprema",
    icon: "Oprema",
    image: null,
    slug: "računarska oprema",
    parent: [],
    description: null,
    for: { demo: "sales-1", type: "categories" },
  },
  {
    id: "83c499b4-3b13-4927-bf75-eae73cd5eff4",
    name: "Printeri",
    icon: "Printer",
    image: null,
    slug: "printeri",
    parent: [],
    description: null,
    for: { demo: "sales-1", type: "categories" },
  },
];

export const subcategories = [
    { name: "Adapteri", slug: "adapteri" },
    { name: "Miševi", slug: "misevi" },
    { name: "Projektori", slug: "projektori" },
    { name: "Diskovi", slug: "diskovi" }, 
    { name: "Tastature", slug: "tastature"},
    { name: "Grafičke kartice", slug: "graficke kartice" }
];
